# ***Inserting Data From Our Local Device***

In [3]:
import pandas as pd
# Reading CSV file through the pandas -
df = pd.read_csv("./sample_data/california_housing_test.csv")
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [15]:
# if we want to target a specific column then try this -

df['latitude']
df['longitude']


pops = df['population'].sum()
print(int(pops))

4208396

In [19]:
# to type-cast the exsisting data we must have to use some methods like -

df.to_json("housing_data.json")
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [25]:
# targeting multiple columns in pandas DF
newTable = df[['total_rooms', 'total_bedrooms', 'median_income', 'median_house_value']]
newTable

      total_rooms  total_bedrooms  median_income  median_house_value
0          3885.0           661.0         6.6085            344700.0
1          1510.0           310.0         3.5990            176500.0
2          3589.0           507.0         5.7934            270500.0
3            67.0            15.0         6.1359            330000.0
4          1241.0           244.0         2.9375             81700.0
...           ...             ...            ...                 ...
2995       1450.0           642.0         1.1790            225000.0
2996       5257.0          1082.0         3.3906            237200.0
2997        956.0           201.0         2.2895             62000.0
2998         96.0            14.0         3.2708            162500.0
2999       1765.0           263.0         8.5608            500001.0

[3000 rows x 4 columns]

In [32]:
# to iterate the first 15 rows of data we can use df.head() method for the top rows of the data and df.tail() for the bottom rows of the data

print(df.head())     # by default .head() will provide only 5 rows of the df, if we want to get more than 5 rows of data we must have to pass a numerical argument in the df

   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.05     37.37                27.0       3885.0           661.0
1    -118.30     34.26                43.0       1510.0           310.0
2    -117.81     33.78                27.0       3589.0           507.0
3    -118.36     33.82                28.0         67.0            15.0
4    -119.67     36.33                19.0       1241.0           244.0

   population  households  median_income  median_house_value
0      1537.0       606.0         6.6085            344700.0
1       809.0       277.0         3.5990            176500.0
2      1484.0       495.0         5.7934            270500.0
3        49.0        11.0         6.1359            330000.0
4       850.0       237.0         2.9375             81700.0

In [33]:
print(df.head(15))     # by default .head() will provide only 5 rows of the df, if we want to get more than 5 rows of data we must have to pass a numerical argument in the df

    longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0     -122.05     37.37                27.0       3885.0           661.0
1     -118.30     34.26                43.0       1510.0           310.0
2     -117.81     33.78                27.0       3589.0           507.0
3     -118.36     33.82                28.0         67.0            15.0
4     -119.67     36.33                19.0       1241.0           244.0
5     -119.56     36.51                37.0       1018.0           213.0
6     -121.43     38.63                43.0       1009.0           225.0
7     -120.65     35.48                19.0       2310.0           471.0
8     -122.84     38.40                15.0       3080.0           617.0
9     -118.02     34.08                31.0       2402.0           632.0
10    -118.24     33.98                45.0        972.0           249.0
11    -119.12     35.85                37.0        736.0           166.0
12    -121.93     37.25                36.0       1089.0           182.0
13    -117.03     32.97                16.0       3936.0           694.0
14    -117.97     33.73                27.0       2097.0           325.0

    population  households  median_income  median_house_value
0       1537.0       606.0         6.6085            344700.0
1        809.0       277.0         3.5990            176500.0
2       1484.0       495.0         5.7934            270500.0
3         49.0        11.0         6.1359            330000.0
4        850.0       237.0         2.9375             81700.0
5        663.0       204.0         1.6635             67000.0
6        604.0       218.0         1.6641             67000.0
7       1341.0       441.0         3.2250            166900.0
8       1446.0       599.0         3.6696            194400.0
9       2830.0       603.0         2.3333            164200.0
10      1288.0       261.0         2.2054            125000.0
11       564.0       138.0         2.4167             58300.0
12       535.0       170.0         4.6900            252600.0
13      1935.0       659.0         4.5625            231200.0
14      1217.0       331.0         5.7121            222500.0

In [34]:
print(df.tail())

      longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
2995    -119.86     34.42                23.0       1450.0           642.0
2996    -118.14     34.06                27.0       5257.0          1082.0
2997    -119.70     36.30                10.0        956.0           201.0
2998    -117.12     34.10                40.0         96.0            14.0
2999    -119.63     34.42                42.0       1765.0           263.0

      population  households  median_income  median_house_value
2995      1258.0       607.0         1.1790            225000.0
2996      3496.0      1036.0         3.3906            237200.0
2997       693.0       220.0         2.2895             62000.0
2998        46.0        14.0         3.2708            162500.0
2999       753.0       260.0         8.5608            500001.0

In [35]:
print(df.tail(15))

      longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
2985    -120.47     34.94                17.0       1368.0           308.0
2986    -118.25     33.93                42.0        819.0           233.0
2987    -121.97     37.29                25.0       4096.0           743.0
2988    -122.01     36.97                43.0       2162.0           509.0
2989    -122.02     37.60                32.0       1295.0           295.0
2990    -118.23     34.09                49.0       1638.0           456.0
2991    -117.17     34.28                13.0       4867.0           718.0
2992    -122.33     37.39                52.0        573.0           102.0
2993    -117.91     33.60                37.0       2088.0           510.0
2994    -117.93     33.86                35.0        931.0           181.0
2995    -119.86     34.42                23.0       1450.0           642.0
2996    -118.14     34.06                27.0       5257.0          1082.0
2997    -119.70     36.30                10.0        956.0           201.0
2998    -117.12     34.10                40.0         96.0            14.0
2999    -119.63     34.42                42.0       1765.0           263.0

      population  households  median_income  median_house_value
2985       642.0       303.0         1.8633            109400.0
2986       899.0       228.0         1.1346             85400.0
2987      2027.0       741.0         5.3294            300300.0
2988      1208.0       464.0         2.5417            260900.0
2989      1097.0       328.0         3.2386            149600.0
2990      1500.0       430.0         2.6923            150000.0
2991       780.0       250.0         7.1997            253800.0
2992       232.0        92.0         6.2263            500001.0
2993       673.0       390.0         5.1048            500001.0
2994       516.0       174.0         5.5867            182500.0
2995      1258.0       607.0         1.1790            225000.0
2996      3496.0      1036.0         3.3906            237200.0
2997       693.0       220.0         2.2895             62000.0
2998        46.0        14.0         3.2708            162500.0
2999       753.0       260.0         8.5608            500001.0