# **Filtering in Pandas**

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('purchases.csv')
df

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,69_MOUNTMEND_8412,69,8412,Tequila Ocho Plata Fresno,750mL,105.0,ALTAMAR BRANDS LLC,8124.0,2023-12-21,2024-01-02,2024-01-04,2024-02-16,35.71,6.0,214.26,1.0
1,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466.0,AMERICAN VINTAGE BEVERAGE,8137.0,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4.0,37.40,1.0
2,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466.0,AMERICAN VINTAGE BEVERAGE,8137.0,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5.0,47.05,1.0
3,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466.0,AMERICAN VINTAGE BEVERAGE,8137.0,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6.0,56.10,1.0
4,76_DONCASTER_2034,76,2034,Glendalough Double Barrel,750mL,388.0,ATLANTIC IMPORTING COMPANY,8169.0,2023-12-24,2024-01-02,2024-01-09,2024-02-16,21.32,5.0,106.60,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1968623,34_PITMERDEN_4334,34,4334,Casa Noble Blanco Crystal,750mL,1392.0,CONSTELLATION BRANDS INC,12840.0,2024-10-31,2024-11-07,2024-11-18,2024-12-23,25.54,6.0,153.24,1.0
1968624,23_ARBINGTON_6420,23,6420,R M Woodbridge Chard Cal,750mL,1392.0,CONSTELLATION BRANDS INC,12840.0,2024-10-31,2024-11-09,2024-11-18,2024-12-23,3.18,10.0,31.80,2.0
1968625,67_EANVERNESS_39598,67,39598,R M Woodbridge Cab Svgn Cal,187mL 4 Pk,1392.0,CONSTELLATION BRANDS INC,12840.0,2024-10-31,2024-11-10,2024-11-18,2024-12-23,4.76,12.0,57.12,2.0
1968626,73_DONCASTER_19748,73,19748,Clos du Bois Chard,1.5L,1392.0,CONSTELLATION BRANDS INC,12840.0,2024-10-31,2024-11-09,2024-11-18,2024-12-23,9.20,3.0,27.60,2.0
1968627,44_PORTHCRAWL_3806,44,3806,Svedka Citron Vodka,75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
filteredProducts = df[df['PurchasePrice'] > 100]
filteredProducts

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
1642,69_MOUNTMEND_2767,69,2767,Johnnie Walker Blue Label,750mL,3960.0,DIAGEO NORTH AMERICA INC,8173.0,2023-12-24,2024-01-01,2024-01-10,2024-02-19,139.70,1.0,139.70,1.0
1764,29_AYLESBURY_2767,29,2767,Johnnie Walker Blue Label,750mL,3960.0,DIAGEO NORTH AMERICA INC,8173.0,2023-12-24,2024-01-02,2024-01-10,2024-02-19,139.70,3.0,419.10,1.0
1902,67_EANVERNESS_2767,67,2767,Johnnie Walker Blue Label,750mL,3960.0,DIAGEO NORTH AMERICA INC,8173.0,2023-12-24,2024-01-02,2024-01-10,2024-02-19,139.70,6.0,838.20,1.0
2299,34_PITMERDEN_2748,34,2748,Johnnie Walker Blue Label,1.75L,3960.0,DIAGEO NORTH AMERICA INC,8173.0,2023-12-24,2024-01-02,2024-01-10,2024-02-19,240.59,2.0,481.18,1.0
2303,78_EASTHAVEN_2767,78,2767,Johnnie Walker Blue Label,750mL,3960.0,DIAGEO NORTH AMERICA INC,8173.0,2023-12-24,2024-01-01,2024-01-10,2024-02-19,139.70,3.0,419.10,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1960924,73_DONCASTER_2247,73,2247,Balvenie Portwood 21 Yr Sin,750mL,3664.0,WILLIAM GRANT & SONS INC,12801.0,2024-10-27,2024-11-03,2024-11-12,2024-12-22,162.69,2.0,325.38,1.0
1960935,38_GOULCREST_2247,38,2247,Balvenie Portwood 21 Yr Sin,750mL,3664.0,WILLIAM GRANT & SONS INC,12801.0,2024-10-27,2024-11-03,2024-11-12,2024-12-22,162.69,3.0,488.07,1.0
1960937,3_HORNSEY_2247,3,2247,Balvenie Portwood 21 Yr Sin,750mL,3664.0,WILLIAM GRANT & SONS INC,12801.0,2024-10-27,2024-10-31,2024-11-12,2024-12-22,162.69,3.0,488.07,1.0
1961112,76_DONCASTER_2368,76,2368,Balvenie 17 Yr Doublewood,750mL,3664.0,WILLIAM GRANT & SONS INC,12801.0,2024-10-27,2024-11-03,2024-11-12,2024-12-22,108.52,18.0,1953.36,1.0
1961288,73_DONCASTER_2368,73,2368,Balvenie 17 Yr Doublewood,750mL,3664.0,WILLIAM GRANT & SONS INC,12801.0,2024-10-27,2024-11-03,2024-11-12,2024-12-22,108.52,6.0,651.12,1.0

In [10]:
filteredBrand = df[df['Brand'] == 2767]
filteredBrand

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
1642,69_MOUNTMEND_2767,69,2767,Johnnie Walker Blue Label,750mL,3960.0,DIAGEO NORTH AMERICA INC,8173.0,2023-12-24,2024-01-01,2024-01-10,2024-02-19,139.7,1.0,139.7,1.0
1764,29_AYLESBURY_2767,29,2767,Johnnie Walker Blue Label,750mL,3960.0,DIAGEO NORTH AMERICA INC,8173.0,2023-12-24,2024-01-02,2024-01-10,2024-02-19,139.7,3.0,419.1,1.0
1902,67_EANVERNESS_2767,67,2767,Johnnie Walker Blue Label,750mL,3960.0,DIAGEO NORTH AMERICA INC,8173.0,2023-12-24,2024-01-02,2024-01-10,2024-02-19,139.7,6.0,838.2,1.0
2303,78_EASTHAVEN_2767,78,2767,Johnnie Walker Blue Label,750mL,3960.0,DIAGEO NORTH AMERICA INC,8173.0,2023-12-24,2024-01-01,2024-01-10,2024-02-19,139.7,3.0,419.1,1.0
18225,57_LANTEGLOS_2767,57,2767,Johnnie Walker Blue Label,750mL,3960.0,DIAGEO NORTH AMERICA INC,8271.0,2023-12-31,2024-01-07,2024-01-14,2024-02-11,139.7,1.0,139.7,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1929704,73_DONCASTER_2767,73,2767,Johnnie Walker Blue Label,750mL,3960.0,DIAGEO NORTH AMERICA INC,12748.0,2024-10-25,2024-11-03,2024-11-09,2024-12-22,139.7,4.0,558.8,1.0
1930441,50_MOUNTMEND_2767,50,2767,Johnnie Walker Blue Label,750mL,3960.0,DIAGEO NORTH AMERICA INC,12748.0,2024-10-25,2024-11-03,2024-11-09,2024-12-22,139.7,9.0,1257.3,1.0
1930596,81_PEMBROKE_2767,81,2767,Johnnie Walker Blue Label,750mL,3960.0,DIAGEO NORTH AMERICA INC,12748.0,2024-10-25,2024-11-05,2024-11-09,2024-12-22,139.7,6.0,838.2,1.0
1930731,67_EANVERNESS_2767,67,2767,Johnnie Walker Blue Label,750mL,3960.0,DIAGEO NORTH AMERICA INC,12748.0,2024-10-25,2024-11-04,2024-11-09,2024-12-22,139.7,6.0,838.2,1.0
1931491,41_LARNWICK_2767,41,2767,Johnnie Walker Blue Label,750mL,3960.0,DIAGEO NORTH AMERICA INC,12748.0,2024-10-25,2024-11-04,2024-11-09,2024-12-22,139.7,6.0,838.2,1.0

# **Merge, Concat & Join Methods**

In [27]:
ds1 = pd.Series(['A', 'B', 'C', 'A', 'A', 'B', 'C'])
ds2 = pd.Series([10, 20, 30, 40, 50, 60, 70])
ds3 = pd.Series(['A', 'B', 'C', 'D', 'A', 'B'])
ds4 = pd.Series([1, 2, 3, 4, 5, 6])

df1 = pd.DataFrame({
    "Prod": ds1,
    "ProdPrice": ds2
})

df2 = pd.DataFrame({
    "Prod": ds3,
    # "ProdPrice": ds2,
    "ProdQuantity": ds4
})

In [15]:
# merge()

mergedDf = pd.merge(df2, df1, on='Prod')
print(df1)
print(df2)
mergedDf

  Prod  ProdPrice
0    A         10
1    B         20
2    C         30
3    A         40
4    A         50
5    B         60
6    C         70
  Prod  ProdQuantity
0    A             1
1    B             2
2    C             3
3    D             4
4    A             5
5    B             6

   Prod  ProdQuantity  ProdPrice
0     A             1         10
1     A             1         40
2     A             1         50
3     B             2         20
4     B             2         60
5     C             3         30
6     C             3         70
7     A             5         10
8     A             5         40
9     A             5         50
10    B             6         20
11    B             6         60

In [19]:
# join() -
print(df1)
print(df2)

joinedDf = df1.join(df2.set_index("Prod"), on='Prod')
joinedDf

  Prod  ProdPrice
0    A         10
1    B         20
2    C         30
3    A         40
4    A         50
5    B         60
6    C         70
  Prod  ProdQuantity
0    A             1
1    B             2
2    C             3
3    D             4
4    A             5
5    B             6

  Prod  ProdPrice  ProdQuantity
0    A         10             1
0    A         10             5
1    B         20             2
1    B         20             6
2    C         30             3
3    A         40             1
3    A         40             5
4    A         50             1
4    A         50             5
5    B         60             2
5    B         60             6
6    C         70             3

In [29]:
# concat() -
newDf = pd.concat([df1, df2], axis=1)
print(df1)
print(df2)
newDf

  Prod  ProdPrice
0    A         10
1    B         20
2    C         30
3    A         40
4    A         50
5    B         60
6    C         70
  Prod  ProdQuantity
0    A             1
1    B             2
2    C             3
3    D             4
4    A             5
5    B             6

  Prod  ProdPrice Prod  ProdQuantity
0    A         10    A           1.0
1    B         20    B           2.0
2    C         30    C           3.0
3    A         40    D           4.0
4    A         50    A           5.0
5    B         60    B           6.0
6    C         70  NaN           NaN