# **Some Pandas Methods With lil bit of analaysis**

In [1]:
import pandas as pd

In [27]:
df = pd.read_csv("purchase_prices.csv")
df

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,58,Gekkeikan Black & Gold Sake,12.99,750mL,750,1,9.28,8320,SHAW ROSS INT L IMP LTD
1,62,Herradura Silver Tequila,36.99,750mL,750,1,28.67,1128,BROWN-FORMAN CORP
2,63,Herradura Reposado Tequila,38.99,750mL,750,1,30.46,1128,BROWN-FORMAN CORP
3,72,No. 3 London Dry Gin,34.99,750mL,750,1,26.11,9165,ULTRA BEVERAGE COMPANY LLP
4,75,Three Olives Tomato Vodka,14.99,750mL,750,1,10.94,7245,PROXIMO SPIRITS INC.
...,...,...,...,...,...,...,...,...,...
12256,44917,Ferreira 10-Yr Tawny Port,24.99,750mL,750,2,16.55,90024,VINILANDIA USA
12257,44944,Sanford Santa Rita Pnt Nr,22.99,750mL,750,2,14.93,4425,MARTIGNETTI COMPANIES
12258,45016,Neal One Lane Bridg Cab Svgn,93.99,750mL,750,2,61.43,10754,PERFECTA WINES
12259,46011,Folonari Pnt Nr Venezie,12.99,1500ml,1500,2,8.90,9744,FREDERICK WILDMAN & SONS
12260,46964,Calera Viognier Mt Harlan,35.99,750mL,750,2,24.32,10754,PERFECTA WINES

In [3]:
df.columns

Index(['Brand', 'Description', 'Price', 'Size', 'Volume', 'Classification',
       'PurchasePrice', 'VendorNumber', 'VendorName'],
      dtype='object')

In [4]:
df.describe()

,Brand,Price,Classification,PurchasePrice,VendorNumber
count,12261.000000,12261.000000,12261.000000,12261.000000,12261.000000
mean,17989.067123,38.640240,1.708996,26.488220,10814.861757
std,12528.503464,206.151172,0.454244,156.182948,19007.682322
min,58.000000,0.000000,1.000000,0.000000,2.000000
25%,5990.000000,10.990000,1.000000,6.890000,3960.000000
50%,18788.000000,15.990000,2.000000,10.650000,7153.000000
75%,25117.000000,29.990000,2.000000,20.130000,9552.000000
max,90631.000000,13999.900000,2.000000,11111.030000,173357.000000

In [5]:
df.describe(include='all')

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
count,12261.000000,12260,12261.000000,12260,12260,12261.000000,12261.000000,12261.000000,12261
unique,NaN,11114,NaN,56,33,NaN,NaN,NaN,136
top,NaN,Bacardi Superior Rum,NaN,750mL,750,NaN,NaN,NaN,MARTIGNETTI COMPANIES
freq,NaN,7,NaN,9823,9840,NaN,NaN,NaN,1631
mean,17989.067123,NaN,38.640240,NaN,NaN,1.708996,26.488220,10814.861757,NaN
std,12528.503464,NaN,206.151172,NaN,NaN,0.454244,156.182948,19007.682322,NaN
min,58.000000,NaN,0.000000,NaN,NaN,1.000000,0.000000,2.000000,NaN
25%,5990.000000,NaN,10.990000,NaN,NaN,1.000000,6.890000,3960.000000,NaN
50%,18788.000000,NaN,15.990000,NaN,NaN,2.000000,10.650000,7153.000000,NaN
75%,25117.000000,NaN,29.990000,NaN,NaN,2.000000,20.130000,9552.000000,NaN
max,90631.000000,NaN,13999.900000,NaN,NaN,2.000000,11111.030000,173357.000000,NaN

In [6]:
df.count()

Brand             12261
Description       12260
Price             12261
Size              12260
Volume            12260
Classification    12261
PurchasePrice     12261
VendorNumber      12261
VendorName        12261
dtype: int64

In [13]:
df['VendorNumber'].unique().size

131

In [17]:
df['VendorName'].unique().size

136

In [32]:
newDf = df.drop(axis=1, columns="Volume")

In [33]:
newDf

,Brand,Description,Price,Size,Classification,PurchasePrice,VendorNumber,VendorName
0,58,Gekkeikan Black & Gold Sake,12.99,750mL,1,9.28,8320,SHAW ROSS INT L IMP LTD
1,62,Herradura Silver Tequila,36.99,750mL,1,28.67,1128,BROWN-FORMAN CORP
2,63,Herradura Reposado Tequila,38.99,750mL,1,30.46,1128,BROWN-FORMAN CORP
3,72,No. 3 London Dry Gin,34.99,750mL,1,26.11,9165,ULTRA BEVERAGE COMPANY LLP
4,75,Three Olives Tomato Vodka,14.99,750mL,1,10.94,7245,PROXIMO SPIRITS INC.
...,...,...,...,...,...,...,...,...
12256,44917,Ferreira 10-Yr Tawny Port,24.99,750mL,2,16.55,90024,VINILANDIA USA
12257,44944,Sanford Santa Rita Pnt Nr,22.99,750mL,2,14.93,4425,MARTIGNETTI COMPANIES
12258,45016,Neal One Lane Bridg Cab Svgn,93.99,750mL,2,61.43,10754,PERFECTA WINES
12259,46011,Folonari Pnt Nr Venezie,12.99,1500ml,2,8.90,9744,FREDERICK WILDMAN & SONS
12260,46964,Calera Viognier Mt Harlan,35.99,750mL,2,24.32,10754,PERFECTA WINES

In [34]:
df.drop(axis=1, columns="Size", inplace=True)

In [36]:
df.drop(axis=1, columns="Volume", inplace=True)

In [37]:
df

,Brand,Description,Price,Classification,PurchasePrice,VendorNumber,VendorName
0,58,Gekkeikan Black & Gold Sake,12.99,1,9.28,8320,SHAW ROSS INT L IMP LTD
1,62,Herradura Silver Tequila,36.99,1,28.67,1128,BROWN-FORMAN CORP
2,63,Herradura Reposado Tequila,38.99,1,30.46,1128,BROWN-FORMAN CORP
3,72,No. 3 London Dry Gin,34.99,1,26.11,9165,ULTRA BEVERAGE COMPANY LLP
4,75,Three Olives Tomato Vodka,14.99,1,10.94,7245,PROXIMO SPIRITS INC.
...,...,...,...,...,...,...,...
12256,44917,Ferreira 10-Yr Tawny Port,24.99,2,16.55,90024,VINILANDIA USA
12257,44944,Sanford Santa Rita Pnt Nr,22.99,2,14.93,4425,MARTIGNETTI COMPANIES
12258,45016,Neal One Lane Bridg Cab Svgn,93.99,2,61.43,10754,PERFECTA WINES
12259,46011,Folonari Pnt Nr Venezie,12.99,2,8.90,9744,FREDERICK WILDMAN & SONS
12260,46964,Calera Viognier Mt Harlan,35.99,2,24.32,10754,PERFECTA WINES

In [39]:
df.duplicated().sum()

np.int64(0)

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12261 entries, 0 to 12260
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Brand           12261 non-null  int64
 1   Description     12260 non-null  object
 2   Price           12261 non-null  float64
 3   Classification  12261 non-null  int64
 4   PurchasePrice   12261 non-null  float64
 5   VendorNumber    12261 non-null  int64
 6   VendorName      12261 non-null  object
dtypes: float64(2), int64(3), object(2)
memory usage: 670.7+ KB

In [42]:
df['Price'] = df['Price'] * 93.08

In [45]:
df['Price'].round(2)

0        1209.11
1        3443.03
2        3629.19
3        3256.87
4        1395.27
          ...
12256    2326.07
12257    2139.91
12258    8748.59
12259    1209.11
12260    3349.95
Name: Price, Length: 12261, dtype: float64

In [46]:
df['PurchasePrice'] = df['PurchasePrice'] * 93.08

In [50]:
df[["Price", "PurchasePrice"]] = df[["Price", "PurchasePrice"]].round(2)

In [51]:
df

,Brand,Description,Price,Classification,PurchasePrice,VendorNumber,VendorName
0,58,Gekkeikan Black & Gold Sake,1209.11,1,863.78,8320,SHAW ROSS INT L IMP LTD
1,62,Herradura Silver Tequila,3443.03,1,2668.60,1128,BROWN-FORMAN CORP
2,63,Herradura Reposado Tequila,3629.19,1,2835.22,1128,BROWN-FORMAN CORP
3,72,No. 3 London Dry Gin,3256.87,1,2430.32,9165,ULTRA BEVERAGE COMPANY LLP
4,75,Three Olives Tomato Vodka,1395.27,1,1018.30,7245,PROXIMO SPIRITS INC.
...,...,...,...,...,...,...,...
12256,44917,Ferreira 10-Yr Tawny Port,2326.07,2,1540.47,90024,VINILANDIA USA
12257,44944,Sanford Santa Rita Pnt Nr,2139.91,2,1389.68,4425,MARTIGNETTI COMPANIES
12258,45016,Neal One Lane Bridg Cab Svgn,8748.59,2,5717.90,10754,PERFECTA WINES
12259,46011,Folonari Pnt Nr Venezie,1209.11,2,828.41,9744,FREDERICK WILDMAN & SONS
12260,46964,Calera Viognier Mt Harlan,3349.95,2,2263.71,10754,PERFECTA WINES

In [63]:
amountSpentInPercentage = (df['PurchasePrice']/df['Price']) * 100
discountedPrice = 100 - amountSpentInPercentage

discountedPrice

df['DiscountApplied'] = discountedPrice

In [64]:
df

,Brand,Description,Price,Classification,PurchasePrice,VendorNumber,VendorName,DiscountApplied
0,58,Gekkeikan Black & Gold Sake,1209.11,1,863.78,8320,SHAW ROSS INT L IMP LTD,28.560677
1,62,Herradura Silver Tequila,3443.03,1,2668.60,1128,BROWN-FORMAN CORP,22.492688
2,63,Herradura Reposado Tequila,3629.19,1,2835.22,1128,BROWN-FORMAN CORP,21.877334
3,72,No. 3 London Dry Gin,3256.87,1,2430.32,9165,ULTRA BEVERAGE COMPANY LLP,25.378661
4,75,Three Olives Tomato Vodka,1395.27,1,1018.30,7245,PROXIMO SPIRITS INC.,27.017710
...,...,...,...,...,...,...,...,...
12256,44917,Ferreira 10-Yr Tawny Port,2326.07,2,1540.47,90024,VINILANDIA USA,33.773704
12257,44944,Sanford Santa Rita Pnt Nr,2139.91,2,1389.68,4425,MARTIGNETTI COMPANIES,35.058951
12258,45016,Neal One Lane Bridg Cab Svgn,8748.59,2,5717.90,10754,PERFECTA WINES,34.642039
12259,46011,Folonari Pnt Nr Venezie,1209.11,2,828.41,9744,FREDERICK WILDMAN & SONS,31.485969
12260,46964,Calera Viognier Mt Harlan,3349.95,2,2263.71,10754,PERFECTA WINES,32.425559

In [67]:
df = df.drop(axis=1, columns="DiscountApplied")

In [68]:
df

,Brand,Description,Price,Classification,PurchasePrice,VendorNumber,VendorName
0,58,Gekkeikan Black & Gold Sake,1209.11,1,863.78,8320,SHAW ROSS INT L IMP LTD
1,62,Herradura Silver Tequila,3443.03,1,2668.60,1128,BROWN-FORMAN CORP
2,63,Herradura Reposado Tequila,3629.19,1,2835.22,1128,BROWN-FORMAN CORP
3,72,No. 3 London Dry Gin,3256.87,1,2430.32,9165,ULTRA BEVERAGE COMPANY LLP
4,75,Three Olives Tomato Vodka,1395.27,1,1018.30,7245,PROXIMO SPIRITS INC.
...,...,...,...,...,...,...,...
12256,44917,Ferreira 10-Yr Tawny Port,2326.07,2,1540.47,90024,VINILANDIA USA
12257,44944,Sanford Santa Rita Pnt Nr,2139.91,2,1389.68,4425,MARTIGNETTI COMPANIES
12258,45016,Neal One Lane Bridg Cab Svgn,8748.59,2,5717.90,10754,PERFECTA WINES
12259,46011,Folonari Pnt Nr Venezie,1209.11,2,828.41,9744,FREDERICK WILDMAN & SONS
12260,46964,Calera Viognier Mt Harlan,3349.95,2,2263.71,10754,PERFECTA WINES

In [69]:
df.insert(5, "DiscountApplied", discountedPrice)

In [70]:
df

,Brand,Description,Price,Classification,PurchasePrice,DiscountApplied,VendorNumber,VendorName
0,58,Gekkeikan Black & Gold Sake,1209.11,1,863.78,28.560677,8320,SHAW ROSS INT L IMP LTD
1,62,Herradura Silver Tequila,3443.03,1,2668.60,22.492688,1128,BROWN-FORMAN CORP
2,63,Herradura Reposado Tequila,3629.19,1,2835.22,21.877334,1128,BROWN-FORMAN CORP
3,72,No. 3 London Dry Gin,3256.87,1,2430.32,25.378661,9165,ULTRA BEVERAGE COMPANY LLP
4,75,Three Olives Tomato Vodka,1395.27,1,1018.30,27.017710,7245,PROXIMO SPIRITS INC.
...,...,...,...,...,...,...,...,...
12256,44917,Ferreira 10-Yr Tawny Port,2326.07,2,1540.47,33.773704,90024,VINILANDIA USA
12257,44944,Sanford Santa Rita Pnt Nr,2139.91,2,1389.68,35.058951,4425,MARTIGNETTI COMPANIES
12258,45016,Neal One Lane Bridg Cab Svgn,8748.59,2,5717.90,34.642039,10754,PERFECTA WINES
12259,46011,Folonari Pnt Nr Venezie,1209.11,2,828.41,31.485969,9744,FREDERICK WILDMAN & SONS
12260,46964,Calera Viognier Mt Harlan,3349.95,2,2263.71,32.425559,10754,PERFECTA WINES

In [73]:
df['DiscountApplied'] = df['DiscountApplied'].round(2)

In [74]:
df

,Brand,Description,Price,Classification,PurchasePrice,DiscountApplied,VendorNumber,VendorName
0,58,Gekkeikan Black & Gold Sake,1209.11,1,863.78,28.56,8320,SHAW ROSS INT L IMP LTD
1,62,Herradura Silver Tequila,3443.03,1,2668.60,22.49,1128,BROWN-FORMAN CORP
2,63,Herradura Reposado Tequila,3629.19,1,2835.22,21.88,1128,BROWN-FORMAN CORP
3,72,No. 3 London Dry Gin,3256.87,1,2430.32,25.38,9165,ULTRA BEVERAGE COMPANY LLP
4,75,Three Olives Tomato Vodka,1395.27,1,1018.30,27.02,7245,PROXIMO SPIRITS INC.
...,...,...,...,...,...,...,...,...
12256,44917,Ferreira 10-Yr Tawny Port,2326.07,2,1540.47,33.77,90024,VINILANDIA USA
12257,44944,Sanford Santa Rita Pnt Nr,2139.91,2,1389.68,35.06,4425,MARTIGNETTI COMPANIES
12258,45016,Neal One Lane Bridg Cab Svgn,8748.59,2,5717.90,34.64,10754,PERFECTA WINES
12259,46011,Folonari Pnt Nr Venezie,1209.11,2,828.41,31.49,9744,FREDERICK WILDMAN & SONS
12260,46964,Calera Viognier Mt Harlan,3349.95,2,2263.71,32.43,10754,PERFECTA WINES

In [76]:
df.isnull().sum()

Brand              0
Description        1
Price              0
Classification     0
PurchasePrice      0
DiscountApplied    1
VendorNumber       0
VendorName         0
dtype: int64